# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘IOSProject’ do

end

target ‘FBProject’ do
	pod ‘FBSDKCoreKit’
	pod ‘FBSDKLoginKit’
	pod ‘FBSDKShareKit’
end